<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Phoenix_QPay
 * @copyright  Copyright (c) 208 Phoenix Medien GmbH & Co. KG (http://www.phoenix-medien.de)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
    echo $this->getMethod()->getTitle() . '<br/>';
    $data = $this->getInfo()->getAdditionalInformation();
    if (!$data) {
        $data = unserialize($this->getInfo()->getAdditionalData());
    }
    if(is_array($data))
    {
        foreach($data AS $key => $value)
        {
            if(strtolower($key) == 'lasttransid')
            {
                echo $this->__('QPay Transaction ID: %s', $this->htmlEscape($value)) . '<br/>';
            }
            else
            {
                echo $this->__($this->htmlEscape($key).': %s', $this->htmlEscape($value)) .'<br />';
            }
        }
    }
    else if($this->getInfo()->getLastTransId())
    {
        echo $this->__('QPay Transaction ID: %s', $this->htmlEscape($this->getInfo()->getLastTransId())) . '<br/>';
    }
    else
    {
        echo $this->__('Payment has not been processed yet.') . '<br/>';
    }
?>
